baseURL = 'https://entredialogos.com'
languageCode = 'pt-PT'
title = 'Entre Diálogos' # This can get overwritten by the single language files
defaultContentLanguage = 'pt'
# defaultContentLanguageInSubDir = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
theme = "Magnolia"
googleAnalytics = ""
description = "Consultas de psicologia online com a Psicóloga Filipa Tavares (OPP 29538). Espaço seguro para tratar ansiedade, relações e autoconhecimento. Marque a sua sessão."

# BLOG
# Uncomment if you want to disable all posts and tags rendering and indexing
ignoreFiles= ['posts/*']
disableKinds = ['taxonomy', 'term', 'RSS']

# Developer area #

#[taxonomies]
#tag = "tags"

# Block AI crawlers to limit traffic
  # robots.txt from https://robotstxt.com/ai
  # Note that enabling this might impact SEO performance, since many search engines now
  # use LLMs that gather data with these crawlers from across the web
[params.robots]
  blockAIcrawlers = false

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'
  # Prints warning if hugo version is too old
  [module.hugoVersion]
    extended = false
    min = '0.129.0'


  
# To render some markdown otherwise unrendered
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true