main:
  - name: "Home"
    url: "/"
    weight: 1

#  - name: "Sobre mim"
#    url: "/about"
#    weight: 2

  # - name: "Consultas"
  #   url: "consultas"
  #   weight: 3

buttons:
  - name: "Marcar consulta"
    url: "https://tr.ee/Wm7adTtyNS"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

#  - name: "Sobre mim"
#    url: "/about"
#    weight: 2

  # - name: "Consultas"
  #   url: "/consultas"
  #   weight: 3

  # - name: "Blog"
  #   url: "/blog"
  #   weight: 4

  - name: "Marcar consulta"
    url: "https://tr.ee/Wm7adTtyNS"
    weight: 5
